name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: vtk
      run: sh ./thirdparty/install-vtk.sh

    - name: hdf5
      run: install-hdf5.sh
      working-directory: ./thirdparty/thirdparty
    - name: make
      run: ./install.sh --enable.vtk --enable.hdf5

    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
